# Generated by Django 3.0.3 on 2020-03-09 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200309_2045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='custom_category',
            new_name='categories',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='custom_source',
            new_name='sources',
        ),
    ]
