# Generated by Django 3.0.3 on 2020-04-06 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20200406_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='account',
            name='sources',
        ),
    ]
