# Generated by Django 3.0.3 on 2020-04-06 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20200406_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='bbcSource',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='categoryPolitics',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='categorySport',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='independentSource',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
