# Generated by Django 3.0.3 on 2020-04-06 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20200406_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='bbcSource',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='categoryCoronaVirus',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='categoryPolitics',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='categorySport',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='independentSource',
            field=models.BooleanField(default=False),
        ),
    ]
