# Generated by Django 3.0.3 on 2020-04-09 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20200406_2004'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScraperData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastScraped', models.DateTimeField(verbose_name='last scraped')),
            ],
        ),
    ]
