# Generated by Django 3.0.3 on 2020-04-09 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_scraperdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraperdata',
            name='name',
            field=models.CharField(default='lastScraped', max_length=30),
        ),
    ]
