# Generated by Django 3.0.3 on 2020-04-15 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_scraperdata_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='categoryCoronaVirus',
            new_name='categoryTech',
        ),
    ]
