# Generated by Django 3.0.3 on 2020-04-15 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20200415_0128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='categoryTech',
        ),
        migrations.AddField(
            model_name='account',
            name='categoryCoronaVirus',
            field=models.BooleanField(default=False, verbose_name='Coronavirus'),
        ),
        migrations.AlterField(
            model_name='account',
            name='bbcSource',
            field=models.BooleanField(default=False, verbose_name='BBC'),
        ),
        migrations.AlterField(
            model_name='account',
            name='categoryPolitics',
            field=models.BooleanField(default=False, verbose_name='politics'),
        ),
        migrations.AlterField(
            model_name='account',
            name='categorySport',
            field=models.BooleanField(default=False, verbose_name='sport'),
        ),
        migrations.AlterField(
            model_name='account',
            name='guardianSource',
            field=models.BooleanField(default=True, verbose_name='The Guardian'),
        ),
        migrations.AlterField(
            model_name='account',
            name='independentSource',
            field=models.BooleanField(default=False, verbose_name='The Independent'),
        ),
    ]
