# Generated by Django 3.0.3 on 2020-04-15 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20200415_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='categoryCoronaVirus',
        ),
        migrations.AddField(
            model_name='account',
            name='categoryTech',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='bbcSource',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='categoryPolitics',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='categorySport',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='guardianSource',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='independentSource',
            field=models.BooleanField(default=False),
        ),
    ]
