# Generated by Django 3.0.3 on 2020-04-19 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20200415_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='categoryTech',
            field=models.BooleanField(default=True),
        ),
    ]
