# Generated by Django 3.0.3 on 2020-04-11 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='title',
            new_name='headline',
        ),
        migrations.RemoveField(
            model_name='article',
            name='subtitle',
        ),
        migrations.AddField(
            model_name='article',
            name='source',
            field=models.CharField(default='Unknown Source', max_length=50),
        ),
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.CharField(max_length=200),
        ),
    ]
