# Generated by Django 3.0.3 on 2020-04-19 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20200411_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='favourite',
            field=models.BooleanField(),
        ),
    ]
